### ISSUE TITLE
Readme links to old rendered file and this fork did not refresh it's pdf yet

### ISSUE THREAD

**Issue by centic9** [osegermany/git-internals-doc#1]
The README still links to the original rendered file from repository `pluralsight/git-internals-pdf` via https://github.com/pluralsight/git-internals-pdf/raw/master/drafts/peepcode-git.pdf

Also the new location at https://github.com/osegermany/git-internals-pdf/raw/master/drafts/peepcode-git.pdf contains the old version without the changes merged here.

Maybe a commit-based Github Action could automate generating the PDF?

**Comment by hoijui** [comment]
Thank you @centic9 ! :-)
indeed... we still have to figure out how to best render the PDF, as there seems to be no script/code/anything in this repo, that lets one generate the PDF.

Your idea (CI generated) was definitely also ours, and what we will try to do.
My current best idea is, to use pandoc somehow, maybe converting the textile files to markdown on the fly and then generating a PDF out of it with [MoVeDo](https://github.com/movedo/MoVeDo/actions/), whichs main task is, to generate a single Markdown file out of many, and then using an other tool (e.g. pandoc again), to generate a PDF out of it.

Please feel free to suggest an other (preferably simpler) way to do it, if you know of any.

**Comment by hoijui** [comment]
NOTE: There is a Rakefile (Ruby version of a Makefile), which has a single task `build`. That one only generates (very basic, unstyled) HTML, though.

**Comment by hoijui** [comment]
Link to a (ugly rendered) PDF is now in the README!
